// =====================================================================
// WARNING: This file was automatically generated by Antigravity AI.
// It contains integration tests for testing the CEX engine's actor flow,
// specifically the BalanceActor and channel communications.
// =====================================================================

use tokio::sync::{mpsc, oneshot};
use std::time::Duration;
use engine::{
    actors::BalanceActor,
    types::{BalanceCommand, BalanceEvent, Side},
};

/// Helper to set up the BalanceActor and returns control channels
fn setup_test_actors() -> (mpsc::Sender<BalanceCommand>, mpsc::Sender<BalanceEvent>) {
    let (cmd_tx, cmd_rx) = mpsc::channel(100);
    let (event_tx, event_rx) = mpsc::channel(100);

    let balance_actor = BalanceActor::new(cmd_rx, event_rx);
    tokio::spawn(balance_actor.run());

    (cmd_tx, event_tx)
}

/// Helper function to assert if a user can lock a specific amount of asset
async fn assert_can_lock(
    cmd_tx: &mpsc::Sender<BalanceCommand>,
    user_id: &str,
    symbol: &str,
    side: Side,
    price: u64,
    quantity: u64,
    should_succeed: bool,
) {
    let (respond_tx, respond_rx) = oneshot::channel();
    cmd_tx.send(BalanceCommand::CheckAndLock {
        user_id: user_id.to_string(),
        symbol: symbol.to_string(),
        side,
        price,
        quantity,
        respond_tx,
    }).await.unwrap();

    let result = respond_rx.await.unwrap();
    if should_succeed {
        assert!(result.is_ok(), "Expected lock to succeed for user {}, but failed", user_id);
    } else {
        assert!(result.is_err(), "Expected lock to fail for user {}, but succeeded", user_id);
    }
}

// =====================================================================
// Test 1: Settlement of Buy Transaction (Taker Buy / Maker Sell)
// =====================================================================
#[tokio::test]
async fn test_settlement_buy_transaction() {
    let (cmd_tx, event_tx) = setup_test_actors();

    // 1. Seed Taker (User 1) with USDT by filling an order where they receive USDT.
    // In Taker Sell / Maker Buy, Taker gets USDT. We trigger this to seed Taker with 1000 USDT.
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(), // Maker gets BTC (which saturates at 0 locked)
        taker_user_id: "user_1".to_string(), // Taker gets 1000 USDT (price 500 * quantity 2)
        taker_side: Side::Sell,
    }).await.unwrap();

    // Seed Maker (User 2) with BTC.
    // In Taker Buy / Maker Sell, Maker receives USDT and Taker receives BTC.
    // We send this to seed Maker with 2 BTC.
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_1".to_string(),
        taker_user_id: "user_2".to_string(), // Taker gets 2 BTC
        taker_side: Side::Buy,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 2. Pre-flight Lock:
    // Taker (User 1) locks 1000 USDT to buy BTC
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Buy, 500, 2, true).await;
    // Maker (User 2) locks 2 BTC to sell
    assert_can_lock(&cmd_tx, "user_2", "BTC_USDT", Side::Sell, 500, 2, true).await;

    // 3. Post-flight Settle: Send Fill Event (Taker Buy / Maker Sell)
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(), // Maker
        taker_user_id: "user_1".to_string(), // Taker
        taker_side: Side::Buy,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 4. Verify Ledger Updates:
    // Taker (User 1) paid USDT and now has 2 BTC available.
    // We verify they have 2 BTC by trying to lock it.
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Sell, 500, 2, true).await;
    
    // Maker (User 2) paid BTC and now has 1000 USDT available.
    // We verify they have 1000 USDT by trying to lock it.
    assert_can_lock(&cmd_tx, "user_2", "BTC_USDT", Side::Buy, 500, 2, true).await;
}

// =====================================================================
// Test 2: Settlement of Sell Transaction (Taker Sell / Maker Buy)
// =====================================================================
#[tokio::test]
async fn test_settlement_sell_transaction() {
    let (cmd_tx, event_tx) = setup_test_actors();

    // 1. Seed Taker (User 1) with 2 BTC
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(),
        taker_user_id: "user_1".to_string(), // Taker gets 2 BTC
        taker_side: Side::Buy,
    }).await.unwrap();

    // Seed Maker (User 2) with 1000 USDT
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(), // Maker gets 1000 USDT
        taker_user_id: "user_1".to_string(),
        taker_side: Side::Sell,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 2. Pre-flight Lock:
    // Taker (User 1) locks 2 BTC to sell
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Sell, 500, 2, true).await;
    // Maker (User 2) locks 1000 USDT to buy
    assert_can_lock(&cmd_tx, "user_2", "BTC_USDT", Side::Buy, 500, 2, true).await;

    // 3. Post-flight Settle: Send Fill Event (Taker Sell / Maker Buy)
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(), // Maker
        taker_user_id: "user_1".to_string(), // Taker
        taker_side: Side::Sell,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 4. Verify Ledger Updates:
    // Taker (User 1) paid BTC and now has 1000 USDT available.
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Buy, 500, 2, true).await;

    // Maker (User 2) paid USDT and now has 2 BTC available.
    assert_can_lock(&cmd_tx, "user_2", "BTC_USDT", Side::Sell, 500, 2, true).await;
}

// =====================================================================
// Test 3: Order Cancellation & Lock Release
// =====================================================================
#[tokio::test]
async fn test_order_cancellation_release() {
    let (cmd_tx, event_tx) = setup_test_actors();

    // 1. Seed User 1 with 1000 USDT
    event_tx.send(BalanceEvent::Fill {
        symbol: "BTC_USDT".to_string(),
        price: 500,
        quantity: 2,
        maker_user_id: "user_2".to_string(),
        taker_user_id: "user_1".to_string(), // Taker gets 1000 USDT
        taker_side: Side::Sell,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 2. Lock the entire 1000 USDT
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Buy, 500, 2, true).await;

    // 3. Try to lock another 1 USDT -> Must fail (all USDT locked)
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Buy, 1, 1, false).await;

    // 4. Cancel Order: Release 1000 USDT
    event_tx.send(BalanceEvent::CancelOrder {
        user_id: "user_1".to_string(),
        symbol: "USDT".to_string(),
        amount: 1000,
    }).await.unwrap();

    tokio::time::sleep(Duration::from_millis(50)).await;

    // 5. Verify funds are available again: Locking 1000 USDT must now succeed!
    assert_can_lock(&cmd_tx, "user_1", "BTC_USDT", Side::Buy, 500, 2, true).await;
}
